# Generated by Django 5.0.3 on 2026-01-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tpo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="backlogs",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="graduation_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="internships",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="projects",
            field=models.TextField(blank=True),
        ),
    ]
