# Generated by Django 5.0.3 on 2026-03-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tpo", "0002_studentprofile_address_studentprofile_backlogs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobprofile",
            name="category",
            field=models.CharField(
                choices=[
                    ("IT", "IT Services"),
                    ("Product", "Product Based"),
                    ("Core", "Core Engineering"),
                    ("Consulting", "Consulting"),
                    ("Startup", "Startup"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobprofile",
            name="description",
            field=models.TextField(
                blank=True, help_text="Job description and requirements"
            ),
        ),
        migrations.AddField(
            model_name="jobprofile",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this job is currently active"
            ),
        ),
    ]
