# Generated by Django 5.0.3 on 2026-03-02 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tpo", "0004_jobapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the training"),
                ),
                (
                    "training_type",
                    models.CharField(
                        choices=[
                            ("technical", "Technical Skills"),
                            ("soft_skills", "Soft Skills"),
                            ("aptitude", "Aptitude Training"),
                            ("interview", "Interview Preparation"),
                            ("workshop", "Workshop"),
                            ("certification", "Certification"),
                            ("other", "Other"),
                        ],
                        default="technical",
                        max_length=20,
                    ),
                ),
                (
                    "instructor",
                    models.CharField(
                        help_text="Trainer/Instructor name", max_length=100
                    ),
                ),
                (
                    "venue",
                    models.CharField(
                        help_text="Training location or online platform", max_length=200
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(help_text="Training start date and time"),
                ),
                (
                    "end_date",
                    models.DateTimeField(help_text="Training end date and time"),
                ),
                ("duration_hours", models.IntegerField(help_text="Duration in hours")),
                (
                    "capacity",
                    models.IntegerField(help_text="Maximum number of participants"),
                ),
                (
                    "registered_count",
                    models.IntegerField(
                        default=0, help_text="Number of registered participants"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether registration is open"
                    ),
                ),
                (
                    "is_online",
                    models.BooleanField(
                        default=False, help_text="Whether this is an online training"
                    ),
                ),
                (
                    "meeting_link",
                    models.URLField(
                        blank=True,
                        help_text="Online meeting link for virtual training",
                        null=True,
                    ),
                ),
                (
                    "prerequisites",
                    models.TextField(
                        blank=True, help_text="Required knowledge or skills"
                    ),
                ),
                (
                    "learning_outcomes",
                    models.TextField(help_text="What participants will learn"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="TrainingRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("attended", "Attended"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="registered",
                        max_length=20,
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Student notes about the training"
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, help_text="Student feedback after completion"
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="tpo.training",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "training")},
            },
        ),
    ]
