# Generated by Django 5.0.3 on 2026-03-02 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tpo", "0005_training_trainingregistration"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume_file", models.FileField(upload_to="resume_analyses/")),
                (
                    "overall_score",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Below Average"),
                            (4, "Average"),
                            (5, "Good"),
                            (6, "Very Good"),
                            (7, "Excellent"),
                            (8, "Outstanding"),
                            (9, "Exceptional"),
                            (10, "Perfect"),
                        ],
                        help_text="Overall resume score (1-10)",
                    ),
                ),
                (
                    "ats_score",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Below Average"),
                            (4, "Average"),
                            (5, "Good"),
                            (6, "Very Good"),
                            (7, "Excellent"),
                            (8, "Outstanding"),
                            (9, "Exceptional"),
                            (10, "Perfect"),
                        ],
                        help_text="Applicant Tracking System score",
                    ),
                ),
                (
                    "structure_score",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Below Average"),
                            (4, "Average"),
                            (5, "Good"),
                            (6, "Very Good"),
                            (7, "Excellent"),
                            (8, "Outstanding"),
                            (9, "Exceptional"),
                            (10, "Perfect"),
                        ],
                        help_text="Resume structure and formatting score",
                    ),
                ),
                (
                    "content_score",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Below Average"),
                            (4, "Average"),
                            (5, "Good"),
                            (6, "Very Good"),
                            (7, "Excellent"),
                            (8, "Outstanding"),
                            (9, "Exceptional"),
                            (10, "Perfect"),
                        ],
                        help_text="Content quality and relevance score",
                    ),
                ),
                (
                    "skills_match",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Below Average"),
                            (4, "Average"),
                            (5, "Good"),
                            (6, "Very Good"),
                            (7, "Excellent"),
                            (8, "Outstanding"),
                            (9, "Exceptional"),
                            (10, "Perfect"),
                        ],
                        help_text="Skills matching score",
                    ),
                ),
                (
                    "experience_score",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Below Average"),
                            (4, "Average"),
                            (5, "Good"),
                            (6, "Very Good"),
                            (7, "Excellent"),
                            (8, "Outstanding"),
                            (9, "Exceptional"),
                            (10, "Perfect"),
                        ],
                        help_text="Experience presentation score",
                    ),
                ),
                (
                    "strengths",
                    models.TextField(help_text="Identified strengths in the resume"),
                ),
                ("weaknesses", models.TextField(help_text="Areas for improvement")),
                (
                    "suggestions",
                    models.TextField(help_text="Specific suggestions for improvement"),
                ),
                (
                    "key_skills_found",
                    models.TextField(
                        help_text="Skills identified from resume analysis"
                    ),
                ),
                (
                    "missing_skills",
                    models.TextField(help_text="Important skills that are missing"),
                ),
                ("analysis_date", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-analysis_date"],
            },
        ),
    ]
