# Generated by Django 6.0.1 on 2026-02-01 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlacementProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_number", models.CharField(blank=True, max_length=20, null=True)),
                ("department", models.CharField(blank=True, max_length=50, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("tenth_percentage", models.FloatField(blank=True, null=True)),
                ("twelfth_percentage", models.FloatField(blank=True, null=True)),
                ("cgpa", models.FloatField(blank=True, null=True)),
                ("backlogs", models.BooleanField(default=False)),
                ("num_backlogs", models.IntegerField(default=0)),
                ("programming_languages", models.TextField(blank=True, null=True)),
                ("core_subjects", models.TextField(blank=True, null=True)),
                ("tools_technologies", models.TextField(blank=True, null=True)),
                ("certifications", models.TextField(blank=True, null=True)),
                ("trainings_attended", models.BooleanField(default=False)),
                (
                    "internship_org",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("internship_duration", models.IntegerField(blank=True, null=True)),
                ("job_roles", models.TextField(blank=True, null=True)),
                (
                    "preferred_domain",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("relocation", models.BooleanField(default=False)),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                (
                    "certificates",
                    models.FileField(blank=True, null=True, upload_to="certificates/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
