# Generated by Django 5.0.3 on 2026-03-06 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("profile_update", "Profile Updated"),
                            ("aptitude_test", "Aptitude Test Completed"),
                            ("technical_problem", "Technical Problem Solved"),
                            ("interview_practice", "Interview Practice Session"),
                            ("resume_upload", "Resume Uploaded"),
                            ("job_application", "Job Application Submitted"),
                            ("training_registered", "Training Registered"),
                            ("wellness_check", "Wellness Check-in"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("points_earned", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional activity data"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("profile", "Profile Completion"),
                            ("aptitude", "Aptitude Preparation"),
                            ("technical", "Technical Skills"),
                            ("interview", "Interview Preparation"),
                            ("resume", "Resume Building"),
                            ("applications", "Job Applications"),
                            ("trainings", "Training Programs"),
                            ("wellness", "Wellness Activities"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(
                        default=0, help_text="Progress percentage (0-100)"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "completed_items",
                    models.JSONField(
                        default=dict, help_text="Track completed items in each category"
                    ),
                ),
                (
                    "total_items",
                    models.JSONField(
                        default=dict, help_text="Track total items in each category"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "category")},
            },
        ),
    ]
